-- 없어진 기록 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN 
    (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID

-- 있었는데요 없었습니다
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS AS I, ANIMAL_OUTS AS O
WHERE (I.ANIMAL_ID = O.ANIMAL_ID) AND (I.DATETIME > O.DATETIME)
ORDER BY I.DATETIME

-- 오랜 기간 보호한 동물(1)
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3

-- 보호소에서 중성화한 동물
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM 
    (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME FROM ANIMAL_INS WHERE SEX_UPON_INTAKE = "Intact Female" or SEX_UPON_INTAKE = "Intact Male") as A,
    (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME = "Spayed Female" or SEX_UPON_OUTCOME = "Neutered Male") as B
WHERE A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY A.ANIMAL_ID

-- https://mungto.tistory.com/282?category=734741
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME 
FROM ANIMAL_INS as I JOIN ANIMAL_OUTS as O 
WHERE I.ANIMAL_ID = O.ANIMAL_ID AND I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY I.ANIMAL_ID