-- https://programmers.co.kr/learn/courses/30/lessons/59045
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM 
    (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME FROM ANIMAL_INS WHERE SEX_UPON_INTAKE = "Intact Female" or SEX_UPON_INTAKE = "Intact Male") as A,
    (SELECT ANIMAL_ID,ANIMAL_TYPE,NAME FROM ANIMAL_OUTS WHERE SEX_UPON_OUTCOME = "Spayed Female" or SEX_UPON_OUTCOME = "Neutered Male") as B
WHERE A.ANIMAL_ID = B.ANIMAL_ID